#!/bin/sh

format_output() {
  printf "\n\033[96m==> Running %s:\033[0m\n" "$*"
  "$@"
  echo
}

command -v rustup >/dev/null && format_output rustup update

command -v cargo-install-update >/dev/null && format_output cargo install-update -a

mise ls > /tmp/mise-before.txt
format_output mise upgrade && eval "$(mise hook-env)"
mise ls > /tmp/mise-after.txt
diff -u0 /tmp/mise-before.txt /tmp/mise-after.txt | sed '/^---/d; /^+++/d; /^@@/d'

command -v pnpm >/dev/null && format_output pnpm update -g

command -v pip-review >/dev/null && format_output pip-review -a

command -v gem >/dev/null && format_output gem update

command -v dotnet >/dev/null && format_output dotnet tool update -g --all

command -v go-global-update >/dev/null && format_output go-global-update

command -v flatpak >/dev/null && format_output flatpak update -y

[ "$SHELL" = "/bin/bash" ] && format_output bash "$HOME/.local/share/blesh/ble.sh" --update
