#!/bin/sh

format_output() {
    printf "\n\033[96m==> Running %s:\033[0m\n" "$*"
    "$@"
    echo
}

# Should run before cargo-update
format_output rustup update

# Should run before mise
format_output cargo install-update -a

command -v mise >/dev/null && format_output mise upgrade

format_output npm -g upgrade

format_output dotnet tool update -g --all

format_output go-global-update

format_output code --update-extensions

format_output atuin update

# Flatpak update if Flatpak is installed
command -v flatpak >/dev/null && format_output flatpak update -y

# Should be last, as it's disruptive
format_output bash "$HOME/.local/share/blesh/ble.sh" --update
