font_family Ubuntu Sans Mono
font_size 15.0
text_composition_strategy 1.5
scrollback_lines -1
paste_actions replace-dangerous-control-codes
enable_audio_bell no
window_alert_on_bell no
remember_window_size  no
initial_window_width  80c
initial_window_height 25c
tab_bar_edge top
tab_bar_style powerline
cursor_shape beam

# Require Shift to click links
mouse_map left click ungrabbed mouse_handle_click selection prompt
mouse_map shift+left click ungrabbed mouse_handle_click link

# Atom One Light color scheme
background #F8F8F8
foreground #2A2B32
cursor #2A2B32

# Normal colors
color0 #000000
color1 #DA3E39
color2 #41933E
color3 #855504
color4 #315EEE
color5 #930092
color6 #0E6FAD
color7 #8E8F96

# Bright colors
color8 #2A2B32
color9 #DA3E39
color10 #41933E
color11 #855504
color12 #315EEE
color13 #930092
color14 #0E6FAD
color15 #FFFEFE
