font_family Cousine
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D7,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B8,U+E700-U+E7C5,U+EA60-U+EC1E,U+F000-U+F2FF,U+F300-U+F372,U+F400-U+F533,U+F0001-U+F1AF0 Symbols Nerd Font
font_size 15.0
text_composition_strategy 1.5
scrollback_lines 2000
scrollback_pager_history_size 4096
paste_actions replace-dangerous-control-codes
enable_audio_bell no
window_alert_on_bell no
remember_window_size yes
initial_window_width 80c
initial_window_height 24c
strip_trailing_spaces always
active_tab_background red
active_tab_font_style bold
inactive_tab_font_style italic

# Smaller bottom split - doesn't work in old versions of kitty
#map ctrl+shift+enter launch --cwd=current --bias=30

# Require Shift to click links
mouse_map left click ungrabbed mouse_handle_click selection prompt
mouse_map shift+left click ungrabbed mouse_handle_click link

# Atom One Light color scheme
background #F8F8F8
foreground #2A2B32
cursor #2A2B32
cursor_text_color background

# Normal colors
color0 #000000
color1 #DA3E39
color2 #41933E
color3 #855504
color4 #315EEE
color5 #930092
color6 #0E6FAD
color7 #8E8F96

# Bright colors
color8 #2A2B32
color9 #DA3E39
color10 #41933E
color11 #855504
color12 #315EEE
color13 #930092
color14 #0E6FAD
color15 #FFFEFE