set-option -g focus-events on
set-option -g history-limit 100000
set-option -g mode-keys vi
set-option -g mouse on
set-option -g prefix2 `
set-option -g renumber-windows on
set-option -gw window-status-current-style bg=red
bind-key ` send-prefix -2
bind-key a command-prompt -p SSH: "new-window -n %1 'ssh %1'"
bind-key '"' split-window -v -c "#{pane_current_path}"
