unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set autoindent
set clipboard=unnamedplus
set shiftwidth=2
set smartindent
set softtabstop=2
set tabstop=2
set wrap

packadd! ale

let g:ale_completion_enabled=1
let g:ale_lsp_show_message_severity='information'
let g:ale_lsp_suggestions=1
let g:ale_open_list=1

set bg=dark
colorscheme catppuccin

filetype plugin indent on

nnoremap gd :ALEGoToDefinition<CR>
nnoremap gr :ALEFindReferences<CR>
